In [12]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np
import argparse
import random as rng
from tqdm import tqdm
im =cv.imread("../out.png", cv.CV_8UC1)

cv.imshow('test', im)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:

# # Find contours
# contours, _ = cv.findContours(im, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
# # Find the convex hull object for each contour
# hull_list = []
# for i in range(len(contours)):
#     hull = cv.convexHull(contours[i])
#     hull_list.append(hull)
# # Draw contours + hull results
# drawing = np.zeros((im.shape[0], im.shape[1], 3), dtype=np.uint8)
# for i in range(len(contours)):
#     color = (rng.randint(0,256), rng.randint(0,256), rng.randint(0,256))
#     cv.drawContours(drawing, contours, i, color)
#     cv.drawContours(drawing, hull_list, i, color)
# # Show in a window
# cv.imshow('Contours', drawing)


In [17]:
%matplotlib tk
mat = np.load('../out.npy')
print(mat)

TRACES_MAX_LENGTH = 20

out = np.zeros_like(mat)
traces_remaining = 0


for i in tqdm(range(mat.shape[0])):
    j = 0
    while j < mat.shape[1]:
        if mat[i,j] == 1:
            indices = np.where(mat[i,j:j+TRACES_MAX_LENGTH] == 2)[0]
            if len(indices) !=0:
                stop = np.max(indices)
                out[i,j:j+stop] = 1
                j += stop
        j+=1
    

plt.imshow(out)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


100%|██████████| 500/500 [00:00<00:00, 3108.92it/s]
